#!/usr/bin/env tsx
/**
 * Generate docs/TOOLS.md from the live tool registry so the documented tool
 * catalog can never drift from the code. CI runs this with `--check` and fails
 * if docs/TOOLS.md is out of date; run without a flag to regenerate it.
 *
 *   npm run gen:tools-doc        # write docs/TOOLS.md
 *   npm run check:tools-doc      # exit 1 if docs/TOOLS.md is stale
 *
 * Auth is read from each tool's `requiresAuth` flag (the single source of
 * truth; see src/tools/types.ts).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { tools } from "../src/tools/index.js";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "../docs/TOOLS.md");

function table(rows: { name: string; description: string }[]): string {
  const lines = ["| Tool | Description |", "| --- | --- |"];
  for (const { name, description } of rows) {
    lines.push(`| \`${name}\` | ${description.trim().replace(/\|/g, "\\|")} |`);
  }
  return lines.join("\n");
}

const open = tools.filter((t) => !t.requiresAuth);
const auth = tools.filter((t) => t.requiresAuth);

const content = `<!-- GENERATED by scripts/gen-tools-doc.ts — do not edit by hand.
     Run \`npm run gen:tools-doc\` after changing tools; CI enforces this. -->
# Tools

${tools.length} tools total. Generated from \`src/tools/index.ts\`.

## No API key required (${open.length})

${table(open)}

## Requires an API key (${auth.length})

Set \`IWMM_API_KEY\` in your MCP client config. Create a key at
<https://iwantmymtg.net/user/api-keys>.

${table(auth)}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing file -> stale */
  }
  if (current !== content) {
    console.error(
      "docs/TOOLS.md is out of date. Run `npm run gen:tools-doc` and commit the result.",
    );
    process.exit(1);
  }
  console.log("docs/TOOLS.md is up to date.");
} else {
  writeFileSync(OUT, content);
  console.log(`Wrote ${OUT} (${tools.length} tools).`);
}
